### ISSUE TITLE
Add functionaltiy

### ISSUE THREAD

**Issue by FoxxMD** [FoxxMD/laravel-doctrine#2]
Hey @evopix I like the [improvements](https://github.com/evopix/laravel-doctrine/tree/l5) you have made to my fork. I'd like to provide some more functionality to the folks still waiting for the official l5 release and seem like you know what you are doing!

Could you make a PR to my repo with changes you made that are general to the project and backward compatible? I could also just make you a collaborator on this repo if that'd be easier. Thanks!

**Comment by evopix** [comment]
Hey @FoxxMD, I apologize for the slow reply. I've created two pull requests (#3 and #4) that contain the majority of the changes I've made.

Let me know if you need anything else!

**Comment by FoxxMD** [comment]
Thanks @evopix! I've merged your changes and added backward compatibility for people using annotations with this fork (so they don't have to change their config files)
